### ISSUE TITLE
U forgot to add the extra source files in here

### ISSUE THREAD

**Issue by TheKitBoi** [Funkin-Undefined-Engine/Undefined-Engine#1]
source/Highscore.hx:20: characters 3-7 : Type not found : NGio
9
source/StoryMenuState.hx:64: characters 32-40 : Type not found : MenuItem
10
source/PlayState.hx:44: lines 44-2348 : ... Defined in this class
11
source/FreeplayState.hx:261: characters 3-7 : Type not found : NGio
12
source/Highscore.hx:37: characters 3-7 : Type not found : NGio
13
source/PauseSubState.hx:16: characters 29-46 : Type not found : MusicBeatSubstate
14
source/PlayState.hx:44: lines 44-2348 : ... Defined in this class
15
source/GameOverSubstate.hx:10: characters 32-49 : Type not found : MusicBeatSubstate
16
source/PlayState.hx:44: lines 44-2348 : ... Defined in this class

**Comment by kitty-girl** [comment]
bro this engine is dead

**Comment by TheKitBoi** [comment]
True
